/* Understudy - Copyright (c) 2026 Hasin Md. Daiyan. All rights reserved. See LICENSE.
 * Derived from the Excel-to-data-provider approach of "Maestro Excel Data Driven Framework",
 * Copyright 2026 Md. Mohai Minul Islam, Apache License 2.0 (see THIRD_PARTY_NOTICES.md).
 * Modified: rewritten to embed data in the generated scripts, per-sheet row variables. */
/*
 * Prepare Data — runs inside the GUI process.
 *
 * Replaces run-server.bat + Config/convert.js + json-server for the GUI:
 *   TestData/**\/*.xlsx  ->  JsonData/<Excel>/<Sheet>.json   (for viewing)
 *                        ->  Scripts/<Excel>/<Sheet>.js      (data embedded)
 *
 * The generated .js files contain the sheet rows directly, so Maestro's
 * runScript no longer needs an HTTP server on port 8080. Output paths are
 * the same as before, so existing flows (runScript: "../Scripts/X/Y.js")
 * keep working without any change.
 */

const fs   = require("fs");
const path = require("path");

const PROJECT_DIR = path.join(__dirname, "..");
const TESTDATA    = path.join(PROJECT_DIR, "TestData");
const JSON_DIR    = path.join(PROJECT_DIR, "JsonData");
const SCRIPTS_DIR = path.join(PROJECT_DIR, "Scripts");
const MARKER      = "// Auto-generated by Maestro Flow Runner";

let XLSX = null;
try { XLSX = require("xlsx"); } catch (_) {}

const safe = s => String(s).trim().replace(/[^a-zA-Z0-9_-]/g, "_");

function findExcel(dir, out) {
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory() && !e.name.startsWith(".")) findExcel(full, out);
    else if (/\.xlsx?$/i.test(e.name) && !e.name.startsWith("~$")) out.push(full);
  }
  return out;
}

// Env variable that selects the row for one sheet, e.g. ROW_TripTestData_WithinCity.
// Each sheet has its own variable, so a flow that uses two Excel files
// (e.g. login + trip data) can run trip row 7 while login stays on row 1.
function rowVar(excelBase, sheetSafe) {
  return "ROW_" + safe(excelBase) + "_" + safe(sheetSafe);
}

// Row 1 = column names. Columns with a blank name and rows with no values
// are ignored, so leftover formatting in Excel never becomes "data".
function sheetRows(ws) {
  // raw:false -> text exactly as Excel shows it (keeps leading zeros, formats dates)
  const aoa = XLSX.utils.sheet_to_json(ws, { header: 1, defval: "", raw: false, blankrows: false });
  if (!aoa.length) return [];
  const heads = aoa[0].map(h => String(h).trim());
  const rows = [];
  for (const line of aoa.slice(1)) {
    const obj = {};
    let any = false;
    heads.forEach((h, i) => {
      if (!h) return;
      const v = line[i] == null ? "" : String(line[i]);
      obj[h] = v;                          // empty cells stay "" so ${output.col} is never undefined
      if (v.trim() !== "") any = true;
    });
    if (any) rows.push(obj);
  }
  return rows;
}

function scriptSource(excelRel, sheet, rows, varName) {
  // ES5 only: Maestro's JS engine is not a full modern Node runtime.
  // Row choice: this sheet's own variable, else ROW_NO (CLI use), else row 1.
  return [
    MARKER + " from " + excelRel + " [" + sheet + "]. Do not edit.",
    "var data = " + JSON.stringify(rows, null, 2) + ";",
    "",
    "var ROW_PICK = typeof " + varName + " != 'undefined' ? " + varName +
      " : (typeof ROW_NO != 'undefined' ? ROW_NO : 1);",
    "var index = parseInt(ROW_PICK, 10) - 1;",
    "var row = data[index];",
    "",
    "if (!row) {",
    "  throw new Error('Row ' + (index + 1) + ' not found in " + sheet.replace(/'/g, "") +
      " (' + data.length + ' rows)');",
    "}",
    "Object.keys(row).forEach(function (key) {",
    "  output[key] = row[key];",
    "});",
    ""
  ].join("\n");
}

// Delete generated files we no longer produce (renamed/removed sheets).
// Only touches files that carry our marker, never hand-written scripts.
function removeStale(dir, keep, log) {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) { removeStale(full, keep, log); continue; }
    if (keep.has(full) || !/\.js$/i.test(e.name)) continue;
    const head = fs.readFileSync(full, "utf8").slice(0, 200);
    if (head.startsWith(MARKER) || head.startsWith("// Auto-generated setup file")) {
      fs.unlinkSync(full);
      log("  [removed stale] " + path.relative(PROJECT_DIR, full) + "\n");
    }
  }
}

/**
 * @param {(text:string)=>void} log  streamed to the GUI console
 * @returns {{ ok:boolean, files:number, sheets:number, errors:string[] }}
 */
function prepareData(log) {
  log = log || (() => {});
  const errors = [];
  if (!XLSX) {
    log("[ERROR] The 'xlsx' package is not installed. Run: npm install\n");
    return { ok: false, files: 0, sheets: 0, errors: ["xlsx missing"] };
  }

  const files = findExcel(TESTDATA, []);
  if (!files.length) log("[WARN] No Excel files found in TestData/\n");

  const written = new Set();
  let sheetCount = 0;

  for (const file of files) {
    const rel      = path.relative(PROJECT_DIR, file).split(path.sep).join("/");
    const baseName = path.basename(file, path.extname(file));
    log("[FILE] " + rel + "\n");
    let wb;
    try { wb = XLSX.readFile(file); }
    catch (e) {
      const msg = rel + ": " + (e.code === "EBUSY" ? "file is locked (close it in Excel)" : e.message);
      errors.push(msg); log("  [ERROR] " + msg + "\n");
      continue;
    }

    for (const sheet of wb.SheetNames) {
      // defval: keep empty cells as "" so ${output.col} is never undefined.
      // raw:false: take the text as Excel shows it (keeps leading zeros,
      // formats dates) — Maestro types text anyway.
      const rows = sheetRows(wb.Sheets[sheet]);
      const name = safe(sheet);

      const jsonOut = path.join(JSON_DIR, baseName, name + ".json");
      const jsOut   = path.join(SCRIPTS_DIR, baseName, name + ".js");
      fs.mkdirSync(path.dirname(jsonOut), { recursive: true });
      fs.mkdirSync(path.dirname(jsOut),   { recursive: true });
      fs.writeFileSync(jsonOut, JSON.stringify(rows, null, 2));
      fs.writeFileSync(jsOut, scriptSource(rel, sheet, rows, rowVar(baseName, name)));
      written.add(jsOut);
      sheetCount++;
      log("  [OK] " + sheet + " -> Scripts/" + baseName + "/" + name + ".js (" + rows.length + " rows)\n");
    }
  }

  // If a file could not be read (e.g. open in Excel), keep old scripts
  // rather than deleting them as stale.
  if (!errors.length) removeStale(SCRIPTS_DIR, written, log);
  log("[DONE] " + files.length + " file(s), " + sheetCount + " sheet(s)" +
      (errors.length ? ", " + errors.length + " error(s)" : "") + "\n");
  return { ok: errors.length === 0, files: files.length, sheets: sheetCount, errors };
}

module.exports = { prepareData, rowVar, SCRIPTS_DIR, JSON_DIR };
